apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcomic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcomic
  template:
    metadata:
      labels:
        app: testcomic
    spec:
      containers:
      - name: testcomic
        image: devops2022.azurecr.io/comicbook:testcomic
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testcomic-service
spec:
  selector:
    app: testcomic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comicIngress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: devopsdaemons.devops2022.de
    http:
      paths:
      - path: "/testcomic"
        pathType: Prefix
        backend:
          service:
            name: testcomic-service
            port:
              number: 80
              